/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabajo;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ruben
 */
public class Formulario extends javax.swing.JFrame {

    XML_SAX sax = new XML_SAX();
    XML_JAXB jaxb = new XML_JAXB();
    XML_DOM dom = new XML_DOM();

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    private File archivo;

    private File getArchivo() {
        this.archivo = new File("equipos_futbol.xml");
        return this.archivo;
    }

    private void setArchivo(File arch) {
        this.archivo = arch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarSAX = new javax.swing.JButton();
        labelNombreArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSalida = new javax.swing.JTextArea();
        btnMostrarJAXB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModificarPosicion = new javax.swing.JButton();
        jTextFieldPosicionAntigua = new javax.swing.JTextField();
        jTextFieldPosicionNueva = new javax.swing.JTextField();
        btnMostrarDom = new javax.swing.JButton();
        jButtonGuardarPosicion = new javax.swing.JButton();
        jTextFieldEstadio = new javax.swing.JTextField();
        jTextFieldPresidente = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldFundacion = new javax.swing.JTextField();
        jTextFieldNombreJugador = new javax.swing.JTextField();
        jTextFieldPosicion_Tabla = new javax.swing.JTextField();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jTextFieldPosicion = new javax.swing.JTextField();
        jTextFieldLiga = new javax.swing.JTextField();
        btnAgregarDom = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrarSAX.setText("Mostrar datos");
        btnMostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSAXActionPerformed(evt);
            }
        });

        labelNombreArchivo.setText("El nombre del archivo es:");

        jTextAreaSalida.setColumns(20);
        jTextAreaSalida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSalida);

        btnMostrarJAXB.setText("Mostrar equipo");
        btnMostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarJAXBActionPerformed(evt);
            }
        });

        jLabel3.setText("Posicion antigua");

        jLabel4.setText("Posicion nueva");

        btnModificarPosicion.setText("Modificar posicion");
        btnModificarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPosicionActionPerformed(evt);
            }
        });

        btnMostrarDom.setText("Mostrar datos");
        btnMostrarDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDomActionPerformed(evt);
            }
        });

        jButtonGuardarPosicion.setText("Guardar posicion");
        jButtonGuardarPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPosicionActionPerformed(evt);
            }
        });

        btnAgregarDom.setText("Agregar");
        btnAgregarDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDomActionPerformed(evt);
            }
        });

        jLabel6.setText("Estadio");

        jLabel7.setText("Nombre equipo");

        jLabel8.setText("Presidente");

        jLabel9.setText("Ciudad");

        jLabel10.setText("Fundacion");

        jLabel12.setText("Posicion ");

        jLabel13.setText("Nombre jugador");

        jLabel14.setText("Nacionalidad");

        jLabel15.setText("Liga");

        jLabel16.setText("Posicion tabla ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombreArchivo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnMostrarSAX)
                                .addGap(95, 95, 95)
                                .addComponent(btnMostrarJAXB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarDom)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldPosicionAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPosicionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModificarPosicion)
                                    .addComponent(jButtonGuardarPosicion))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPosicion_Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAgregarDom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel8)))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addComponent(jTextFieldPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel9))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel15))))
                    .addComponent(jTextFieldLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarSAX)
                    .addComponent(btnMostrarJAXB)
                    .addComponent(btnMostrarDom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPosicionAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldPosicionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarPosicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardarPosicion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPosicion_Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarDom)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSAXActionPerformed
        //Recupero el fichero
        if (getArchivo() == null) {
            this.labelNombreArchivo.setText("Vuelve a seleccionar el fichero");
        } else {
            //Abro el fichero
            if (sax.abrir_XML_SAX(getArchivo()) == -1) {
                this.labelNombreArchivo.setText("Error al crear el objeto SAX");
                this.btnMostrarSAX.setEnabled(false);

            } else {
                this.labelNombreArchivo.setText("Se ha abierto el archivo para SAX");
                this.btnMostrarSAX.setEnabled(true);
            }
        }
        //Recorro y muestro el texto
        this.jTextAreaSalida.setText(sax.recorrerSAX(getArchivo()));
    }//GEN-LAST:event_btnMostrarSAXActionPerformed

    private void btnMostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarJAXBActionPerformed
        if (getArchivo() == null) {
            this.labelNombreArchivo.setText("Vuelve a seleccionar el fichero");
        } else {
            if (jaxb.abrir_XML_JAXB(getArchivo()) == -1) {
                this.labelNombreArchivo.setText("Error al crear el objeto JAXB");
                this.btnMostrarSAX.setEnabled(false);
            } else {
                this.labelNombreArchivo.setText("Se ha abierto el archivo para JAXB");
                this.btnMostrarSAX.setEnabled(false);
            }
        }

        this.jTextAreaSalida.setText(jaxb.recorrerJAXB());
    }//GEN-LAST:event_btnMostrarJAXBActionPerformed

    private void btnModificarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPosicionActionPerformed
        if (jaxb.modificarPosicionTabla(this.jTextFieldPosicionAntigua.getText().trim(), this.jTextFieldPosicionNueva.getText()) == -1) {
            labelNombreArchivo.setText("Error al modificar posición");
        } else {
            //Pinta otra vez el texto con la nueva posición que he puesto 
            this.jTextAreaSalida.setText(jaxb.recorrerJAXB());
            labelNombreArchivo.setText("Esta bien modificada la posición");
        }
    }//GEN-LAST:event_btnModificarPosicionActionPerformed

    private void btnMostrarDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDomActionPerformed
        if (getArchivo() == null) {
            this.labelNombreArchivo.setText("Vuelve a seleccionar el fichero");
        } else {
            if (dom.abrir_XML_DOM(getArchivo()) == -1) {
                this.labelNombreArchivo.setText("Error al crear el objeto DOM");
                this.btnMostrarSAX.setEnabled(false);
            } else {
                this.labelNombreArchivo.setText("Se ha abierto el archivo para DOM");
                this.btnMostrarSAX.setEnabled(false);
            }
        }

        jTextAreaSalida.setText(dom.recorrer_DOM_y_mostrar());
    }//GEN-LAST:event_btnMostrarDomActionPerformed

    private void jButtonGuardarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPosicionActionPerformed
        jaxb.guardar_XML_JAXB();
    }//GEN-LAST:event_jButtonGuardarPosicionActionPerformed

    private void btnAgregarDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDomActionPerformed
        if (dom.annadirDom(this.jTextFieldEstadio.getText(), this.jTextFieldPresidente.getText(), this.jTextFieldNombre.getText(), this.jTextFieldCiudad.getText(),
                this.jTextFieldFundacion.getText(), this.jTextFieldPosicion_Tabla.getText(), this.jTextFieldPosicion.getText(), this.jTextFieldNombreJugador.getText(), this.jTextFieldNacionalidad.getText(), this.jTextFieldLiga.getText()) == 1) {
            this.labelNombreArchivo.setText("Error al añadir el equipo");

        } else {
            dom.guardarDOM(getArchivo());
            this.labelNombreArchivo.setText("Equipo añadido correctamente");
            dom.abrir_XML_DOM(getArchivo());
            jTextAreaSalida.setText(dom.recorrer_DOM_y_mostrar());
        }
    }//GEN-LAST:event_btnAgregarDomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDom;
    private javax.swing.JButton btnModificarPosicion;
    private javax.swing.JButton btnMostrarDom;
    private javax.swing.JButton btnMostrarJAXB;
    private javax.swing.JButton btnMostrarSAX;
    private javax.swing.JButton jButtonGuardarPosicion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSalida;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldEstadio;
    private javax.swing.JTextField jTextFieldFundacion;
    private javax.swing.JTextField jTextFieldLiga;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreJugador;
    private javax.swing.JTextField jTextFieldPosicion;
    private javax.swing.JTextField jTextFieldPosicionAntigua;
    private javax.swing.JTextField jTextFieldPosicionNueva;
    private javax.swing.JTextField jTextFieldPosicion_Tabla;
    private javax.swing.JTextField jTextFieldPresidente;
    private javax.swing.JLabel labelNombreArchivo;
    // End of variables declaration//GEN-END:variables
}
